name: recall
description: "Recall - A Flutter application."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.2.0
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.4.0
  just_audio: ^0.9.42
  auto_size_text: ^3.0.0
  confetti: ^0.8.0
  cached_network_image: ^3.3.1
  go_router: ^13.2.0
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.0.0
  http_interceptor: ^2.0.0
  socket_io_client: ^2.0.3+1
  share_plus: ^7.2.1
  url_launcher: ^6.2.4
  intl: ^0.19.0
  flutter_email_sender: ^7.0.0
  cupertino_icons: ^1.0.2
  pdf: ^3.10.7
  path_provider: ^2.1.2
  open_file: ^3.3.2
  permission_handler: ^11.3.0
  image: ^4.1.7

  # RevenueCat Dependencies
  purchases_flutter: ^9.2.1  # Latest version for Flutter 3.29+ compatibility

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # flutter_launcher_icons: ^0.14.1 # Commented out since launcher icons are disabled

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/backgrounds/

# flutter_native_splash:
#   color: "#ffffff" # Background color of the splash screen
#   image: assets/images/splash_screen.png # Path to your splash screen image
#   android: true # Enable for Android
#   ios: true # Enable for iOS
#   web: false # Set to true if you want a web splash screen
#   android_gravity: fill # Ensures the image fills the screen on Android
#   ios_content_mode: scaleToFill # Ensures the image fills the screen on iOS

# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/icon.png"
#   adaptive_icon_background: "assets/images/icon_background.png" # Background image or color
#   adaptive_icon_foreground: "assets/images/icon_foreground.png"
#   remove_alpha_ios: true